code

equ	trap_Print							-1
equ	trap_Error							-2
equ	trap_Milliseconds					-3
equ	trap_Cvar_Register					-4
equ	trap_Cvar_Update					-5
equ	trap_Cvar_Set						-6
equ	trap_Cvar_VariableStringBuffer		-7
equ	trap_Argc							-8
equ	trap_Argv							-9
equ	trap_Args							-10
equ	trap_FS_FOpenFile					-11
equ	trap_FS_Seek			-90
equ	trap_FS_Read						-12
equ	trap_FS_Write						-13 
equ	trap_FS_FCloseFile					-14
equ	trap_SendConsoleCommand				-15
equ	trap_AddCommand						-16
equ	trap_RemoveCommand					-17
equ	trap_SendClientCommand				-18
equ	trap_UpdateScreen						-19
equ	trap_CM_LoadMap						-20
equ	trap_CM_NumInlineModels				-21
equ	trap_CM_InlineModel					-22
equ	trap_CM_LoadModel					-23
equ	trap_CM_TempBoxModel					-24
equ	trap_CM_PointContents				-25
equ	trap_CM_TransformedPointContents	-26
equ	trap_CM_BoxTrace					-27
equ	trap_CM_TransformedBoxTrace		-28	
equ	trap_CM_MarkFragments				-29
equ	trap_S_StartSound					-30
equ	trap_S_StartLocalSound				-31
equ	trap_S_ClearLoopingSounds			-32
equ	trap_S_AddLoopingSound			-33	
equ	trap_S_AddRealLoopingSound			-34
equ	trap_S_StopLoopingSound			-35
equ	trap_S_UpdateEntityPosition			-36
equ	trap_S_Respatialize					-37
equ	trap_S_RegisterSound				-38
equ	trap_S_StopBackgroundTrack			-40
equ	trap_S_StartBackgroundTrack			-41
equ	trap_R_LoadWorldMap				-42	
equ	trap_R_RegisterModel				-43
equ	trap_R_RegisterFont					-44
equ	trap_R_RegisterSkin					-45
equ	trap_R_RegisterShader				-46
equ	trap_R_RegisterShaderNoMip			-47
equ	trap_R_RemapShader				-48
equ	trap_R_ClearScene					-49
equ	trap_R_AddRefEntityToScene			-50
equ	trap_R_AddPolyToScene				-51
equ	trap_R_AddPolysToScene				-52
equ	trap_R_AddLightToScene				-53
equ	trap_R_AddAdditiveLightToScene		-54
equ	trap_R_RenderScene				-55	
equ	trap_R_SetColor					-56	
equ	trap_R_DrawStretchPic				-57
equ	trap_R_ModelBounds				-58	
equ	trap_R_LerpTag					-59	
equ	trap_R_LightForPoint				-60
equ	trap_R_inPVS						-61
equ	trap_GetGlconfig					-62
equ	trap_GetGameState					-63
equ	trap_GetCurrentSnapshotNumber		-64
equ	trap_GetSnapshot					-65
equ	trap_GetServerCommand				-66
equ	trap_GetCurrentCmdNumber			-67
equ	trap_GetUserCmd					-68	
equ	trap_SetUserCmdValue				-69
equ	trap_MemoryRemaining				-70
equ trap_Key_IsDown					-71
equ trap_Key_GetCatcher					-72
equ trap_Key_SetCatcher					-73
equ trap_Key_GetKey						-74
equ trap_RealTime						-75
equ trap_snapv3						-76
equ trap_CIN_PlayCinematic				-77
equ trap_CIN_StopCinematic				-78
equ trap_CIN_RunCinematic 				-79
equ trap_CIN_DrawCinematic				-80
equ trap_CIN_SetExtents					-81
equ trap_CM_TempCapsuleModel			-82
equ trap_CM_CapsuleTrace				-83
equ trap_CM_TransformedCapsuleTrace		-84
equ trap_GetEntityToken					-85

equ	memset						-101
equ	memcpy						-102
equ	strncpy						-103
equ	sin							-104
equ	cos							-105
equ	atan2						-106
equ	sqrt						-107
equ	floor						-108
equ	ceil						-109
equ	acos						-110
equ	asin						-111
equ	atan						-112

equ	testPrintInt				-113
equ	testPrintFloat				-114
