code

equ	trap_Print                            -1
equ	trap_Error                            -2
equ	trap_Milliseconds                     -3
equ	trap_cvarregister                    -4
equ	trap_cvarupdate                      -5
equ	trap_cvarsetstr                         -6
equ	trap_cvargetstrbuf        -7
equ	trap_Argc                             -8
equ	trap_Argv                             -9
equ	trap_Args                             -10
equ	trap_FS_FOpenFile                     -11
equ	trap_FS_Seek                          -12
equ	trap_FS_Read                          -13
equ	trap_FS_Write                         -14
equ	trap_FS_FCloseFile                    -15
equ	trap_SendConsoleCommand               -16
equ	trap_AddCommand                       -17
equ	trap_RemoveCommand                    -18
equ	trap_SendClientCommand                -19
equ	trap_UpdateScreen                     -20
equ	trap_CM_LoadMap                       -21
equ	trap_CM_NumInlineModels               -22
equ	trap_CM_InlineModel                   -23
equ	trap_CM_LoadModel                     -24
equ	trap_CM_TempBoxModel                  -25
equ	trap_CM_PointContents                 -26
equ	trap_CM_TransformedPointContents      -27
equ	trap_CM_BoxTrace                      -28
equ	trap_CM_TransformedBoxTrace           -29
equ	trap_CM_MarkFragments                 -30
equ	trap_S_StartSound                     -31
equ	trap_S_StartLocalSound                -32
equ	trap_S_ClearLoopingSounds             -33
equ	trap_S_AddLoopingSound                -34
equ	trap_S_AddRealLoopingSound            -35
equ	trap_S_StopLoopingSound               -36
equ	trap_S_UpdateEntityPosition           -37
equ	trap_S_Respatialize                   -38
equ	trap_S_RegisterSound                  -39
equ	trap_S_StopBackgroundTrack            -40
equ	trap_S_StartBackgroundTrack           -41
equ	trap_R_LoadWorldMap                   -42
equ	trap_R_RegisterModel                  -43
equ	trap_R_RegisterFont                   -44
equ	trap_R_RegisterSkin                   -45
equ	trap_R_RegisterShader                 -46
equ	trap_R_RegisterShaderNoMip            -47
equ	trap_R_RemapShader                    -48
equ	trap_R_ClearScene                     -49
equ	trap_R_AddRefEntityToScene            -50
equ	trap_R_AddPolyToScene                 -51
equ	trap_R_AddPolysToScene                -52
equ	trap_R_AddLightToScene                -53
equ	trap_R_AddAdditiveLightToScene        -54
equ	trap_R_RenderScene                    -55
equ	trap_R_SetColor                       -56
equ	trap_R_DrawStretchPic                 -57
equ	trap_R_ModelBounds                    -58
equ	trap_R_LerpTag                        -59
equ	trap_R_LightForPoint                  -60
equ	trap_R_inPVS                          -61
equ	trap_GetGlconfig                      -62
equ	trap_GetGameState                     -63
equ	trap_GetCurrentSnapshotNumber         -64
equ	trap_GetSnapshot                      -65
equ	trap_GetServerCommand                 -66
equ	trap_GetCurrentCmdNumber              -67
equ	trap_GetUserCmd                       -68
equ	trap_SetUserCmdValue                  -69
equ	trap_MemoryRemaining                  -70
equ	trap_Key_IsDown                       -71
equ	trap_Key_GetCatcher                   -72
equ	trap_Key_SetCatcher                   -73
equ	trap_Key_GetKey                       -74
equ	trap_RealTime                         -75
equ	trap_snapv3                           -76
equ	trap_CIN_PlayCinematic                -77
equ	trap_CIN_StopCinematic                -78
equ	trap_CIN_RunCinematic                 -79
equ	trap_CIN_DrawCinematic                -80
equ	trap_CIN_SetExtents                   -81
equ	trap_CM_TempCapsuleModel              -82
equ	trap_CM_CapsuleTrace                  -83
equ	trap_CM_TransformedCapsuleTrace       -84
equ	trap_GetEntityToken                   -85

equ	memset                                -86
equ	memcpy                                -87
equ	strncpy                               -88
equ	sin                                   -89
equ	cos                                   -90
equ	atan2                                 -91
equ	sqrt                                  -92
equ	floor                                 -93
equ	ceil                                  -94
equ	acos                                  -95
equ	asin                                  -96
equ	atan                                  -97

equ	testPrintInt                          -98
equ	testPrintFloat                        -99
