#define Psound		"sound"
#define Pmusic		Psound "/music"
#define Pfeedback	Psound "/feedback"
#define Pplayersounds	Psound "/player"
#define Pannounce	Pplayersounds "/announce"

#define Pvis		"vis"
#define Pgraphics	Pvis "/graphics"
#define Pmenuart	Pgraphics "/menu"
#define Pmodels	Pvis "/models"
